<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true" CodeFile="booking.aspx.cs" Inherits="Admin_booking" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h2>Show all Bookings</h2>
                        <h5>Welcome hetvi vaja , Love to see you back. </h5>
                    </div>
                </div>
                <!-- /. ROW  -->
                <hr>
                <center>
                    <h1>Booking Details</h1>
                </center>
                <hr>
                <asp:GridView ID="GridView1" runat="server" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" Font-Size="X-Large" ForeColor="Black" Height="300px" Width="1430px" AutoGenerateColumns="False" DataKeyNames="seat" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
                        <asp:BoundField DataField="fromd" HeaderText="fromd" SortExpression="fromd" />
                        <asp:BoundField DataField="tod" HeaderText="tod" SortExpression="tod" />
                        <asp:BoundField DataField="preairline" HeaderText="preairline" SortExpression="preairline" />
                        <asp:BoundField DataField="preseat" HeaderText="preseat" SortExpression="preseat" />
                        <asp:BoundField DataField="seat" HeaderText="seat" SortExpression="seat" />
                        <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                        <asp:BoundField DataField="time" HeaderText="time" SortExpression="time" />
                        <asp:BoundField DataField="adult" HeaderText="adult" SortExpression="adult" />
                        <asp:BoundField DataField="chil" HeaderText="chil" SortExpression="chil" />
                        <asp:BoundField DataField="infant" HeaderText="infant" SortExpression="infant" />
                        <asp:BoundField DataField="fare" HeaderText="fare" SortExpression="fare" />
                        <asp:BoundField DataField="redate" HeaderText="redate" SortExpression="redate" />
                        <asp:BoundField DataField="retime" HeaderText="retime" SortExpression="retime" />
                        <asp:BoundField DataField="message" HeaderText="message" SortExpression="message" />
                        <asp:BoundField DataField="fname" HeaderText="fname" SortExpression="fname" />
                        <asp:BoundField DataField="phone" HeaderText="phone" SortExpression="phone" />
                        <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" />
                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#808080" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#383838" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Airline1ConnectionString %>" SelectCommand="SELECT * FROM [booking]" UpdateCommand="UPDATE [booking] SET fromd=@fromd, tod=@tod, preairline=@preairline, preseat=@preseat, date=@date, time=@time, adult=@adult, chil=@chil, infant=@infant, fare=@fare, redate=@redate, retime=@retime, message=@message, fname=@fname, phone=@phone, email=@email where seat=@seat" DeleteCommand="delete from booking where seat=@seat"></asp:SqlDataSource>
            </div>
        </div>
</asp:Content>

